<a href="https://colab.research.google.com/github/piusAI/AllAboutDL/blob/main/part_01_01_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [7]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
x = dataset.iloc[:, :-1 ].values
y = dataset.iloc[:, -1 ].values

In [8]:
print("Feature:\n", x)

print("\n Target: \n", y)

Feature:
 [[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]

 Target: 
 [463.26 444.37 488.56 ... 429.57 435.74 453.28]


Target, label로 실제 정답값이고,

classification과 다르게 regression은 predict값이 float, 실수로 나온다!

### Encoding categorical data

Label Encoding the "Gender" column

One Hot Encoding the "Geography" column

### Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 0)

### Feature Scaling

## Part 2 - Building the ANN

### Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [13]:
ann.add(tf.keras.layers.Dense(units =1))

=> Regression하면 최종적으로 연속적인 실수 예측해야해서 Activation 함수 안했다

## Part 3 - Training the ANN

### Compiling the ANN

Optimizer?

In [14]:
ann.compile(optimizer='adam', loss = "mean_squared_error")

adam algorithm으로 MSE 로 loss function잡음

### Training the ANN on the Training set

In [15]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 86409.4609
Epoch 2/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 496.7542
Epoch 3/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 377.5497
Epoch 4/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 326.8069
Epoch 5/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 261.4802
Epoch 6/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 203.1450
Epoch 7/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 149.8983
Epoch 8/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 102.8459
Epoch 9/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 69.6802
Epoch 10/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53.7593
Epoch 11/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 42.3890
Epoch 12/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 38.2078
Epoch 13/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37.2186
Epoch 14/100
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34.7269
Epoch 15/100
270/27

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [24]:
y_pred = ann.predict(x_test, batch_size=32)
np.set_printoptions(precision=2) # 소수점 두개만 parameter로
print( np.concatenate(( y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1 ) )
 # concatenate를 활용해서
 # [Predict - Label] 확인

30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
[[431.78 431.23]
 [462.73 460.01]
 [466.22 461.14]
 ...
 [438.61 440.36]
 [454.33 451.22]
 [441.34 439.56]]


**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

### Making the Confusion Matrix