<a href="https://colab.research.google.com/github/piusAI/AllAboutDL/blob/main/section04_01_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [9]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [10]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [11]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1 ].values
y = dataset.iloc[:, -1 ].values

In [12]:
print("Feature:\n", X)

print("\n Target: \n", y)

Feature:
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

 Target: 
 [1 0 1 ... 1 1 0]


Target, label로 실제 정답값이고,

classification과 다르게 regression은 predict값이 float, 실수로 나온다!

### Encoding categorical data

Label Encoding the "Gender" column

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2]) # Exchange Female:0, Male:1

In [14]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer( transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

<Preprocess, Template 활용해서>

Geopgraphy, 지역을 one-hot code로 수정함

In [20]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

### Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

Standard Scaler!

- 특성 1: 나이 = [20, 30, 40]
- 특성 2: 연봉 = [30,000,000, 60,000,000, 100,000,000]

이렇게 각각의 Feature Scale의 차이를 없애주는것


```
# X_scaled = (X - 평균) / 표준편차

```



| 특성 | 평균  | 표준편차 | 스케일링 결과              |
| -- | --- | ---- | -------------------- |
| 나이 | 30  | 10   | \[-1, 0, 1]          |
| 연봉 | 63M | 29M  | \[-1.14, -0.1, 1.24] |


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units =1))

=> Regression하면 최종적으로 연속적인 실수 예측해야해서 Activation 함수 안했다

## Part 3 - Training the ANN

### Compiling the ANN

Optimizer?

In [ ]:
ann.compile(optimizer='adam', loss = "mean_squared_error")

adam algorithm으로 MSE 로 loss function잡음

### Training the ANN on the Training set

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [ ]:
y_pred = ann.predict(x_test, batch_size=32)
np.set_printoptions(precision=2) # 소수점 두개만 parameter로
print( np.concatenate(( y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1 ) )
 # concatenate를 활용해서
 # [Predict - Label] 확인

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

### Making the Confusion Matrix